In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('kidney_disease.csv')

In [3]:
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
df.isnull()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
398,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
399,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [6]:
ctd=['id','sg','al','sc','htn','cad']

In [7]:
kai=df.drop(columns=ctd)

In [8]:
kai.shape

(400, 20)

In [9]:
kai.isnull().sum()

age                 9
bp                 12
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
dm                  2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [10]:
kai.dropna(inplace=True)

In [11]:
kai.isnull().sum()

age               0
bp                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
dm                0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [12]:
kai

,age,bp,su,rbc,pc,pcc,ba,bgr,bu,sod,pot,hemo,pcv,wc,rc,dm,appet,pe,ane,classification
3,48.0,70.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,111.0,2.5,11.2,32,6700,3.9,no,poor,yes,yes,ckd
9,53.0,90.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,114.0,3.7,9.5,29,12100,3.7,yes,poor,no,yes,ckd
11,63.0,70.0,0.0,abnormal,abnormal,present,notpresent,380.0,60.0,131.0,4.2,10.8,32,4500,3.8,yes,poor,yes,no,ckd
14,68.0,80.0,2.0,normal,abnormal,present,present,157.0,90.0,130.0,6.4,5.6,16,11000,2.6,yes,poor,yes,no,ckd
20,61.0,80.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,148.0,135.0,5.2,7.7,24,9200,3.2,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,150.0,4.9,15.7,47,6700,4.9,no,good,no,no,notckd
396,42.0,70.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,141.0,3.5,16.5,54,7800,6.2,no,good,no,no,notckd
397,12.0,80.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,137.0,4.4,15.8,49,6600,5.4,no,good,no,no,notckd
398,17.0,60.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,135.0,4.9,14.2,51,7200,5.9,no,good,no,no,notckd
399,58.0,80.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,141.0,3.5,15.8,53,6800,6.1,no,good,no,no,notckd

In [13]:
label_encoder = LabelEncoder()
kai['rbc']= label_encoder.fit_transform(kai['rbc'])
kai['pc']= label_encoder.fit_transform(kai['pc'])
kai['pcc']= label_encoder.fit_transform(kai['pcc'])
kai['ba']= label_encoder.fit_transform(kai['ba'])
kai['dm']= label_encoder.fit_transform(kai['dm'])
kai['classification']=label_encoder.fit_transform(kai['classification'])
kai['pe']=label_encoder.fit_transform(kai['pe'])
kai['ane']=label_encoder.fit_transform(kai['ane'])
kai['appet']=label_encoder.fit_transform(kai['appet'])

In [14]:
kai

,age,bp,su,rbc,pc,pcc,ba,bgr,bu,sod,pot,hemo,pcv,wc,rc,dm,appet,pe,ane,classification
3,48.0,70.0,0.0,1,0,1,0,117.0,56.0,111.0,2.5,11.2,32,6700,3.9,0,1,1,1,0
9,53.0,90.0,0.0,0,0,1,0,70.0,107.0,114.0,3.7,9.5,29,12100,3.7,1,1,0,1,0
11,63.0,70.0,0.0,0,0,1,0,380.0,60.0,131.0,4.2,10.8,32,4500,3.8,1,1,1,0,0
14,68.0,80.0,2.0,1,0,1,1,157.0,90.0,130.0,6.4,5.6,16,11000,2.6,1,1,1,0,0
20,61.0,80.0,0.0,0,0,0,0,173.0,148.0,135.0,5.2,7.7,24,9200,3.2,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,0.0,1,1,0,0,140.0,49.0,150.0,4.9,15.7,47,6700,4.9,0,0,0,0,1
396,42.0,70.0,0.0,1,1,0,0,75.0,31.0,141.0,3.5,16.5,54,7800,6.2,0,0,0,0,1
397,12.0,80.0,0.0,1,1,0,0,100.0,26.0,137.0,4.4,15.8,49,6600,5.4,0,0,0,0,1
398,17.0,60.0,0.0,1,1,0,0,114.0,50.0,135.0,4.9,14.2,51,7200,5.9,0,0,0,0,1
399,58.0,80.0,0.0,1,1,0,0,131.0,18.0,141.0,3.5,15.8,53,6800,6.1,0,0,0,0,1

In [15]:
kai['classification'].unique()

array([0, 1])

In [16]:
kai['classification'].value_counts()

1    115
0     43
Name: classification, dtype: int64

In [17]:
kai.shape

(158, 20)

In [18]:
x=kai.iloc[:,0:-1]
y=kai.iloc[:,-1]

In [19]:
x.shape

(158, 19)

In [20]:
y.shape

(158,)

In [21]:
x

,age,bp,su,rbc,pc,pcc,ba,bgr,bu,sod,pot,hemo,pcv,wc,rc,dm,appet,pe,ane
3,48.0,70.0,0.0,1,0,1,0,117.0,56.0,111.0,2.5,11.2,32,6700,3.9,0,1,1,1
9,53.0,90.0,0.0,0,0,1,0,70.0,107.0,114.0,3.7,9.5,29,12100,3.7,1,1,0,1
11,63.0,70.0,0.0,0,0,1,0,380.0,60.0,131.0,4.2,10.8,32,4500,3.8,1,1,1,0
14,68.0,80.0,2.0,1,0,1,1,157.0,90.0,130.0,6.4,5.6,16,11000,2.6,1,1,1,0
20,61.0,80.0,0.0,0,0,0,0,173.0,148.0,135.0,5.2,7.7,24,9200,3.2,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,0.0,1,1,0,0,140.0,49.0,150.0,4.9,15.7,47,6700,4.9,0,0,0,0
396,42.0,70.0,0.0,1,1,0,0,75.0,31.0,141.0,3.5,16.5,54,7800,6.2,0,0,0,0
397,12.0,80.0,0.0,1,1,0,0,100.0,26.0,137.0,4.4,15.8,49,6600,5.4,0,0,0,0
398,17.0,60.0,0.0,1,1,0,0,114.0,50.0,135.0,4.9,14.2,51,7200,5.9,0,0,0,0
399,58.0,80.0,0.0,1,1,0,0,131.0,18.0,141.0,3.5,15.8,53,6800,6.1,0,0,0,0

In [22]:
y

3      0
9      0
11     0
14     0
20     0
      ..
395    1
396    1
397    1
398    1
399    1
Name: classification, Length: 158, dtype: int32

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y ,random_state=10 )
x_train

,age,bp,su,rbc,pc,pcc,ba,bgr,bu,sod,pot,hemo,pcv,wc,rc,dm,appet,pe,ane
285,66.0,70.0,0.0,1,1,0,0,94.0,19.0,135.0,3.9,16.0,41,5300,5.9,0,0,0,0
398,17.0,60.0,0.0,1,1,0,0,114.0,50.0,135.0,4.9,14.2,51,7200,5.9,0,0,0,0
371,28.0,60.0,0.0,1,1,0,0,79.0,50.0,145.0,5.0,17.6,51,6500,5.0,0,0,0,0
267,48.0,80.0,0.0,1,1,0,0,122.0,33.0,146.0,3.9,13.9,48,9500,4.8,0,0,0,0
393,43.0,60.0,0.0,1,1,0,0,117.0,45.0,141.0,4.4,13.0,54,7400,5.4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,29.0,80.0,0.0,1,1,0,0,83.0,49.0,139.0,3.3,17.5,40,9900,4.7,0,0,0,0
272,56.0,80.0,0.0,1,1,0,0,139.0,15.0,135.0,5.0,14.8,42,5600,5.5,0,0,0,0
92,71.0,70.0,0.0,1,0,1,1,219.0,82.0,133.0,4.4,10.4,33,5600,3.6,1,0,0,0
364,73.0,80.0,0.0,1,1,0,0,118.0,44.0,137.0,3.5,14.8,45,9300,4.7,0,0,0,0
71,46.0,60.0,0.0,1,1,0,0,163.0,92.0,141.0,4.0,9.8,28,14600,3.2,1,0,0,0

In [25]:
x_train.shape

(118, 19)

In [26]:
x_test.shape

(40, 19)

In [27]:
y_train.shape

(118,)

In [28]:

y_test.shape

(40,)

In [29]:



from sklearn.tree import DecisionTreeClassifier

In [30]:

clf_gini=DecisionTreeClassifier(criterion='gini',random_state=0)
clf_gini.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [31]:

p=clf_gini.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
print(accuracy_score(p,y_test))

0.975

In [34]:
kai

,age,bp,su,rbc,pc,pcc,ba,bgr,bu,sod,pot,hemo,pcv,wc,rc,dm,appet,pe,ane,classification
3,48.0,70.0,0.0,1,0,1,0,117.0,56.0,111.0,2.5,11.2,32,6700,3.9,0,1,1,1,0
9,53.0,90.0,0.0,0,0,1,0,70.0,107.0,114.0,3.7,9.5,29,12100,3.7,1,1,0,1,0
11,63.0,70.0,0.0,0,0,1,0,380.0,60.0,131.0,4.2,10.8,32,4500,3.8,1,1,1,0,0
14,68.0,80.0,2.0,1,0,1,1,157.0,90.0,130.0,6.4,5.6,16,11000,2.6,1,1,1,0,0
20,61.0,80.0,0.0,0,0,0,0,173.0,148.0,135.0,5.2,7.7,24,9200,3.2,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,0.0,1,1,0,0,140.0,49.0,150.0,4.9,15.7,47,6700,4.9,0,0,0,0,1
396,42.0,70.0,0.0,1,1,0,0,75.0,31.0,141.0,3.5,16.5,54,7800,6.2,0,0,0,0,1
397,12.0,80.0,0.0,1,1,0,0,100.0,26.0,137.0,4.4,15.8,49,6600,5.4,0,0,0,0,1
398,17.0,60.0,0.0,1,1,0,0,114.0,50.0,135.0,4.9,14.2,51,7200,5.9,0,0,0,0,1
399,58.0,80.0,0.0,1,1,0,0,131.0,18.0,141.0,3.5,15.8,53,6800,6.1,0,0,0,0,1

In [35]:

import pickle

In [36]:
with open("model.pkl",'wb') as file:
    pickle.dump(clf_gini,file)

# import pickle
import numpy as np

# Load the trained model
with open("model.pkl", 'rb') as file:
    model = pickle.load(file)

print("Model Loaded Successfully!")

# Function to take user input
def get_user_input():
    print("\nEnter the values one by one:")
    
    Age = float(input("Enter Age: "))
    Bp = float(input("Enter Blood Pressure (Bp): "))
    Su = float(input("Enter Sugar Level (Su): "))
    Rbc = int(input("Enter RBC Count (0 or 1): "))
    Pc = int(input("Enter Pc (0 or 1): "))
    Pcc = int(input("Enter Pcc (0 or 1): "))
    Ba = int(input("Enter Ba (0 or 1): "))
    Bgr = float(input("Enter Blood Glucose Random (Bgr): "))
    Bu = float(input("Enter Blood Urea (Bu): "))
    Sod = float(input("Enter Sodium (Sod): "))
    Pot = float(input("Enter Potassium (Pot): "))
    Hemo = float(input("Enter Hemoglobin (Hemo): "))
    Pcv = int(input("Enter PCV: "))
    Wc = int(input("Enter White Blood Cell Count (Wc): "))
    Rc = float(input("Enter Red Blood Cell Count (Rc): "))
    Dm = int(input("Enter Diabetes Mellitus (0 or 1): "))
    Appet = int(input("Enter Appetite (0 or 1): "))
    Pe = int(input("Enter Pedal Edema (0 or 1): "))
    Ane = int(input("Enter Anemia (0 or 1): "))

    # Convert input into a NumPy array for prediction
    user_data = np.array([[Age, Bp, Su, Rbc, Pc, Pcc, Ba, Bgr, Bu, Sod, Pot, Hemo, Pcv, Wc, Rc, Dm, Appet, Pe, Ane]])
    
    return user_data

# Get user input
user_data = get_user_input()

# Predict output
prediction = model.predict(user_data)

# Display result
if prediction[1] == 0:
    print("\n🔴 High Chance of Heart Attack")
else:
    print("\n🟢 Low Chance of Heart Attack")